# https://taskfile.dev

version: 3

vars:
  flags: -Wall -Werror -std=c17
  include_path: /opt/homebrew/include
  lib_path: /opt/homebrew/lib

tasks:
  build:
    requires:
      vars: [app]
    cmd: |
      clang {{ .flags }} -I{{ .include_path }} -L{{ .lib_path }} \
      -lraylib -o ./build/{{ .app }} ./src/{{ .app }}.c

  default:
    requires:
      vars: [app]
    cmds:
      - task: build
      - task: run

  download:mnist: # looping over vars is still an experimental feature in Task
    vars:
      base_url: http://yann.lecun.com/exdb/mnist
      train_images: train-images-idx3-ubyte.gz
      train_labels: train-labels-idx1-ubyte.gz
      test_images: t10k-images-idx3-ubyte.gz
      test_labels: t10k-labels-idx1-ubyte.gz
    cmds:
      - curl {{ .base_url }}/{{ .train_images }} -o ./data/{{ .train_images }}
      - curl {{ .base_url }}/{{ .train_labels }} -o ./data/{{ .train_labels }}
      - curl {{ .base_url }}/{{ .test_images }} -o ./data/{{ .test_images }}
      - curl {{ .base_url }}/{{ .test_labels }} -o ./data/{{ .test_labels }}
      - gzip -d ./data/{{ .train_images }}
      - gzip -d ./data/{{ .train_labels }}
      - gzip -d ./data/{{ .test_images }}
      - gzip -d ./data/{{ .test_labels }}

  install:
    cmds:
      - brew install raylib
      - brew install gzip

  list:
    cmd: task --list-all

  run:
    dir: ./build
    requires:
      vars: [app]
    cmd: ./{{ .app }}
